### ISSUE TITLE
Pull request: issues with character encoding and comment formatting

### ISSUE THREAD

**Issue by JGLAHE** [PatrickKueck/FASconCAT-G#8] opened 2022-02-23 03:46 UTC
Hi Patrick,

I've found that commend option (-g) is assigned to both 'Replace missing sequences with' and 'Preface', and these are also linked to both (-g) and (-x) in the comments.

I've resolved this command conflict by setting 'Replace missing sequences with' to (-g) and 'Preface' to (-x); I've also made some minor character corrections in comments.

However, I haven't made the pull request because I'm having trouble with the encoding of your name, and with inconsistencies in the comment formating when I upload the .pl file to my forked repo (https://github.com/JGLAHE/FASconCAT-G)].

Would you be able to assist me with this?

Best regards,

James

**Comment by PatrickKueck** [comment] 2022-02-23 11:27
Hi James.

First, thank you for fixing the -g bug. Since I got a pull request from you, I think you could solve the pull request problem? I have a question to you too. This is also my first pull request.  I would like to transfer your changed file into my repository, but I don't know how to merge your changes with my .pl code. There should be an other solution than downloading and re-uploading the new FcC-G perl file from your repository to mine.

Can you help me with this?

Best wishes

Patrick

**Comment by JGLAHE** [comment] 2022-02-24 11:24
Hi Patrick,

Unfortunately, I've never made a pull request either, or done anything with git/github other that post comments, so I'm flying blind too, but I'll make the pull request again: this should allow you to accept it and then apply for my commit permission (which I'll look out for), and then once I've granted that, you should be able make the commit. I'm still not sure where 'push' part comes in, but the commit part seems like it'll do the merging...

I have a deadline tomorrw on some work so I'm unable to fix the issues with the comment misalignments and the ü encoding issue, but those are mainly cosmetic. I didn't set out to translate parts of your comments; because my VSCode rendered ü into something similar to <?>, it didn't initially connect that those words were actually in German - my appologies for that.

I will look out for the commit approval request, but I may not be able to deal with it immediately, at least not until tomorrow afternoon (say ~early Friday morning your time).

Cheers,

James

**Comment by PatrickKueck** [comment] 2022-02-25 09:35
Hi James.

Again, thank you for your great help! I merged and confirmed your pull request. Either I missed that link button the last time or it wasn't there. I am sorry for my confusion. Keep fingers crossed that we two 'half blinds' can manage your pull request :)

Would you mind to do further conversation via email (maybe you have some ideas about how FcC-G can be improved  in the future as well)? In case you like the idea, my email is p.kueck[at]leibniz-zfmk.de but I am also fine if you think otherwise. 

However, looking forward to read from you 

Cheers

Patrick

**Closed as completed** 2023-01-12 01:21 UTC
